export type LanguageCode = 'en' | 'zu'

export const LANGUAGES: Record<LanguageCode, string> = {
  en: 'English',
  zu: 'isiZulu',
}

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    'nav.landing': 'Home',
    'nav.auth': 'Sign in',
    'nav.welcome': 'Welcome',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.onboarding': 'Get Started',
    'nav.marketplace': 'Find a Consultant',
    'nav.connectionRequests': 'Connection Requests',
    'nav.consultantServices': 'My Services & Rates',
    'nav.consultantProfile': 'Consultant Profile',
    'nav.consultantVerification': 'Consultant Verification',
    'nav.availability': 'Availability',
    'nav.mySmes': 'My SMEs',
    'nav.programs': 'Programs',
    'nav.inquiries': 'Inquiries',
    'nav.applicationTracker': 'Application Tracker',
    'nav.metrics': 'Metrics',
    'nav.tracker': 'Tracker',
    'nav.staff': 'Staff',
    'nav.viewAll': 'View All',
    'nav.operations': 'Operations',
    'nav.timesheet': 'Timesheet',
    'nav.manageTeam': 'Manage Team',
    'nav.activity': 'Activity',
    'nav.tasks': 'Tasks',
    'nav.participants': 'SMEs',
    'nav.applications': 'Applications',
    'nav.incubatees': 'Incubatees',
    'nav.compliance': 'Compliance',
    'nav.riskRegister': 'Risk Register',
    'nav.impactAnalysis': 'Impact Analysis',
    'nav.diagnosticPlans': 'Diagnostic Plans',
    'nav.myDiagnosticPlan': 'My Diagnostic Plan',
    'nav.interventions': 'Interventions',
    'nav.documentLibrary': 'Document Library',
    'nav.assignInterventions': 'Assign interventions',
    'nav.assignedInterventions': 'Assigned to me',
    'nav.feedback': 'Feedback',
    'nav.monitoring': 'Monitoring',
    'nav.assignments': 'Assignments',
    'nav.appointments': 'Appointments',
    'nav.movs': 'MOVs',
    'nav.surveys': 'Surveys',
    'nav.surveyBuilder': 'Survey builder',
    'nav.courses': 'Courses',
    'nav.courseBuilder': 'Course builder',
    'nav.reports': 'Reports',
    'nav.esgScorecard': 'ESG Scorecard',
    'nav.esgPerformance': 'Individual ESG Performance',
    'nav.portfolio': 'Portfolio',
    'nav.sectors': 'Sectors',
    'nav.programPerformance': 'Program Performance',
    'nav.structure': 'Departments & Offices',
    'nav.changeRequests': 'Change Requests',
    'nav.assistant': 'Agent Assistant',
    'nav.setup': 'Setup',
    'nav.incubateeWorkspace': 'Incubatee Workspace',
    'nav.roadmap': 'Roadmap',
    'nav.businessPlan': 'Business Plan',
    'nav.strategicPlan': 'Strategic Plan',
    'nav.pitchCoach': 'Pitch Coach',
    'nav.agentRegistry': 'Agent Registry',
    'nav.agentAvailability': 'Agent Availability',
    'nav.agentRatings': 'Agent Ratings',
    'nav.users': 'Users',
    'nav.usageAnalytics': 'Usage Analytics',
    'nav.emailOperations': 'Email Operations',
    'nav.settings': 'Settings',
    'nav.companySettings': 'Company Settings',
    'consultant.common.assignments': 'Assignments',
    'consultant.common.intervention': 'Intervention',
    'consultant.common.sme': 'SME',
    'consultant.common.program': 'Programme',
    'consultant.common.progress': 'Progress',
    'consultant.common.due': 'Due',
    'consultant.common.noDueDate': 'No due date',
    'consultant.status.pending': 'Pending',
    'consultant.status.inprogress': 'In progress',
    'consultant.status.completed': 'Completed',
    'consultant.status.rejected': 'Rejected',
    'consultant.status.overdue': 'Overdue',
    'consultant.metrics.assigned': 'Assigned',
    'consultant.metrics.inProgress': 'In progress',
    'consultant.metrics.completed': 'Completed',
    'consultant.metrics.attention': 'Attention',
    'consultant.dashboard.title': 'Consultant Workspace',
    'consultant.dashboard.subtitle': 'Your delivery queue, feedback signals, and reporting snapshots in one place.',
    'consultant.dashboard.loading': 'Loading consultant workspace',
    'consultant.dashboard.openInterventions': 'Open interventions',
    'consultant.dashboard.assignedHint': 'All interventions assigned to you',
    'consultant.dashboard.pendingHint': '{count} waiting for acceptance',
    'consultant.dashboard.completionHint': '{rate}% completion rate',
    'consultant.dashboard.overdueHint': 'Overdue work items',
    'consultant.dashboard.deliveryQueue': 'Current Delivery Queue',
    'consultant.dashboard.noActive': 'No active interventions assigned to you.',
    'consultant.dashboard.deliveryHealth': 'Delivery Health',
    'consultant.dashboard.noAssignments': 'No assignment data yet',
    'consultant.dashboard.recentFeedback': 'Recent Feedback',
    'consultant.dashboard.noFeedback': 'Feedback will appear after SMEs complete reviews.',
    'consultant.dashboard.averageFeedback': 'Average feedback rating',
    'consultant.dashboard.reviewFeedback': 'Review feedback',
    'consultant.dashboard.buildReport': 'Build report',
    'consultant.feedback.title': 'Feedback',
    'consultant.feedback.loading': 'Loading feedback',
    'consultant.feedback.filters': 'Feedback filters',
    'consultant.feedback.search': 'Search SME, intervention, or comment',
    'consultant.feedback.exportCsv': 'Export CSV',
    'consultant.feedback.average': 'Average',
    'consultant.feedback.lowRatings': 'Low ratings',
    'consultant.feedback.lowRatingsHint': '2 stars or below',
    'consultant.feedback.newest': 'Newest first',
    'consultant.feedback.oldest': 'Oldest first',
    'consultant.feedback.highest': 'Highest rating',
    'consultant.feedback.lowest': 'Lowest rating',
    'consultant.feedback.ratingDistribution': 'Rating Distribution',
    'consultant.feedback.noRated': 'No rated feedback yet',
    'consultant.feedback.comments': 'Comments',
    'consultant.feedback.empty': 'No feedback matches the current filters.',
    'consultant.feedback.noComment': 'No written comment captured.',
    'consultant.feedback.noDate': 'Date not captured',
    'consultant.feedback.unrated': 'Unrated',
    'consultant.feedback.starLabel': '{count} star',
    'consultant.feedback.feedbackCount': 'Feedback count',
    'consultant.feedback.ratings': 'Ratings',
    'consultant.feedback.rating': 'Rating',
    'consultant.feedback.comment': 'Comment',
    'consultant.reports.loading': 'Loading report data',
    'consultant.reports.scope': 'Report scope',
    'consultant.reports.thisMonth': 'This month',
    'consultant.reports.thisQuarter': 'This quarter',
    'consultant.reports.thisYear': 'This year',
    'consultant.reports.custom': 'Custom',
    'consultant.reports.template': 'Template',
    'consultant.reports.downloadCsv': 'Download CSV',
    'consultant.reports.activeHint': '{count} in progress',
    'consultant.reports.avgRating': 'Avg rating',
    'consultant.reports.ratedHint': '{count} rated',
    'consultant.reports.statusMix': 'Status Mix',
    'consultant.reports.programmeWorkload': 'Programme Workload',
    'consultant.reports.empty': 'No report data in this period',
    'consultant.reports.noProgrammeData': 'No programme data in this period',
    'consultant.reports.detail': 'Report Detail',
    'consultant.reports.narrative': 'Narrative summary',
    'consultant.reports.summary': 'Completed {completed} of {total} assigned interventions, with {overdue} items needing attention.',
    'consultant.reports.templateNote': 'This dataset uses the same operations report template link, so operations can download a consultant-specific CSV and drop the values into the standard report pack.',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.create': 'Create',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.backHome': 'Back home',
    'common.dashboard': 'Go to dashboard',
    'common.lightMode': 'Light',
    'common.darkMode': 'Dark',
    'common.search': 'Search',
    'common.logout': 'Logout',
    'common.close': 'Close',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.role': 'Role',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.all': 'All',
    'common.progress': 'Progress',
    'common.noDate': 'No date',
    'common.noCode': 'No code',
    'common.refresh': 'Refresh',
    'common.overview': 'Overview',
    'common.business': 'Business',
    'common.noEmail': 'No email',
    'common.unassigned': 'Unassigned',
    'common.type': 'Type',
    'common.document': 'Document',
    'common.verification': 'Verification',
    'common.owner': 'Owner',
    'common.phone': 'Phone',
    'common.completed': 'completed',
    'common.sector': 'Sector',
    'common.province': 'Province',
    'common.beeLevel': 'B-BBEE level',
    'common.gender': 'Gender',
    'common.score': 'Score',
    'common.review': 'Review',
    'common.view': 'View',
    'common.expiry': 'Expiry',
    'common.notes': 'Notes',
    'common.file': 'File',
    'common.saving': 'Saving...',
    'common.download': 'Download',
    'permissions.featureAccess': 'Feature access',
    'permissions.fullAccess': 'Full feature access',
    'permissions.assignInterventions': 'Assign interventions',
    'permissions.trackInterventions': 'Track intervention progress',
    'permissions.viewDiagnosticPlans': 'View diagnostic plans',
    'permissions.manageDiagnosticPlans': 'Create and edit diagnostic plans',
    'permissions.viewApplications': 'View applications',
    'permissions.manageApplications': 'Review and decide applications',
    'permissions.viewParticipants': 'View SMEs',
    'permissions.viewCompliance': 'View compliance records',
    'permissions.manageCompliance': 'Manage compliance records',
    'permissions.viewReports': 'View reports',
    'director.programs.title': 'Program Performance',
    'director.programs.loading': 'Loading program performance',
    'director.programs.loadError': 'Program performance could not be loaded.',
    'director.programs.programs': 'Programs',
    'director.programs.smes': 'SMEs',
    'director.programs.overdue': 'Overdue',
    'director.programs.filters': 'Program filters',
    'director.programs.search': 'Search programs',
    'director.programs.progressChart': 'Program Progress',
    'director.programs.riskChart': 'Risk Mix by Program',
    'director.programs.avgProgress': 'Avg progress',
    'director.programs.completion': 'Completion',
    'director.programs.highRisk': 'High risk',
    'director.programs.program': 'Program',
    'director.programs.revenue': 'Revenue',
    'director.programs.empty': 'No programs match the current filters.',
    'director.risk.low': 'Low',
    'director.risk.medium': 'Medium',
    'director.risk.high': 'High',
    'director.structure.title': 'Departments and Offices',
    'director.structure.loading': 'Loading structure setup',
    'director.structure.loadError': 'Structure setup could not be loaded.',
    'director.structure.saveError': 'Structure setup could not be saved.',
    'director.structure.saved': 'Structure setup saved.',
    'director.structure.departments': 'Departments',
    'director.structure.department': 'Department',
    'director.structure.offices': 'Offices',
    'director.structure.office': 'Office',
    'director.structure.activeDepartments': 'Active departments',
    'director.structure.activeOffices': 'Active offices',
    'director.structure.notEnabled': 'Departments and offices are not enabled for this company.',
    'director.structure.enableHint': 'Enable departments or branches/offices in Company Settings first, or submit a setup addition request.',
    'director.structure.filters': 'Structure filters',
    'director.structure.search': 'Search name, code, or manager',
    'director.structure.add': 'Add',
    'director.structure.empty': 'No structure records match the current filters.',
    'director.structure.manager': 'Manager',
    'director.structure.code': 'Code',
    'director.structure.managerName': 'Manager name',
    'director.structure.managerEmail': 'Manager email',
    'director.structure.notes': 'Notes',
    'director.structure.nameRequired': 'Name is required.',
    'director.reports.title': 'Director Reports',
    'director.reports.loading': 'Loading director reports',
    'director.reports.loadError': 'Director report data could not be loaded.',
    'director.reports.scope': 'Director report scope',
    'director.reports.programHealth': 'Program Health',
    'director.reports.sectorExposure': 'Sector Exposure',
    'director.reports.riskDistribution': 'Portfolio Risk Distribution',
    'director.reports.smes': 'SMEs',
    'director.reports.sme': 'SME',
    'director.reports.growth': 'Growth',
    'director.reports.risk': 'Risk',
    'director.reports.noPortfolio': 'No portfolio records found.',
    'director.reports.noSectors': 'No sector exposure found.',
    'admin.dashboard.title': 'System Overview',
    'admin.dashboard.subtitle': 'Monitor platform accounts, active projects, application volume, and recent delivery errors.',
    'admin.dashboard.users': 'Users',
    'admin.dashboard.activeUsers': 'Active users',
    'admin.dashboard.companies': 'Companies',
    'admin.dashboard.recentErrors': 'Recent errors',
    'admin.dashboard.source': 'Source',
    'admin.dashboard.error': 'Error',
    'admin.dashboard.recorded': 'Recorded',
    'admin.dashboard.noErrors': 'No recent delivery errors.',
    'admin.dashboard.loadError': 'System overview could not be loaded.',
    'emailOps.title': 'Email operations',
    'emailOps.sent': 'Sent',
    'emailOps.failed': 'Failed',
    'emailOps.rejected': 'Rejected',
    'emailOps.bounced': 'Bounced',
    'emailOps.suppressed': 'Suppressed',
    'emailOps.invalid': 'Invalid emails',
    'emailOps.delivery': 'Delivery activity',
    'emailOps.send': 'Send email',
    'emailOps.queue': 'Queue email',
    'emailOps.queued': 'Email queued for delivery.',
    'emailOps.loadError': 'Email delivery activity could not be loaded.',
    'emailOps.sendError': 'Email could not be queued.',
    'emailOps.recipient': 'Recipient',
    'emailOps.source': 'Source',
    'emailOps.detail': 'Detail',
    'emailOps.reason': 'Reason',
    'emailOps.failures': 'Failures',
    'emailOps.recorded': 'Recorded',
    'emailOps.subject': 'Subject',
    'emailOps.message': 'Message',
    'emailOps.bounceHint': 'Bounce totals require feedback from your SMTP provider. Immediate provider rejections and suppressed addresses are tracked here.',
    'common.moreFilters': 'More filters',
    'common.filters': 'Filters',
    'common.applyFilters': 'Apply filters',
    'common.continue': 'Continue',
    'operations.common.needsAction': 'Needs action',
    'operations.staff.members': 'Staff members',
    'operations.staff.consultants': 'Consultants',
    'operations.staff.consultant': 'Consultant',
    'operations.staff.projectAdmins': 'Project admins',
    'operations.staff.projectAdmin': 'Project admin',
    'operations.staff.directory': 'Staff directory',
    'operations.staff.search': 'Search staff',
    'operations.staff.add': 'Add staff member',
    'operations.staff.edit': 'Edit staff member',
    'operations.staff.save': 'Save staff member',
    'operations.staff.empty': 'No staff match your search.',
    'operations.staff.removeConfirm': 'Remove this staff record?',
    'operations.staff.loadError': 'Staff could not be loaded.',
    'operations.staff.updated': 'Staff member updated.',
    'operations.staff.added': 'Staff member added.',
    'operations.staff.saveError': 'Staff member could not be saved.',
    'operations.staff.removed': 'Staff member removed.',
    'operations.staff.removeError': 'Staff member could not be removed.',
    'operations.participants.enterprise': 'SME Name',
    'operations.participants.programme': 'Program',
    'operations.participants.stage': 'Stage',
    'operations.participants.compliant': 'Compliant',
    'operations.participants.completedInterventions': 'Completed interventions',
    'operations.participants.search': 'Search SMEs',
    'operations.participants.allProgrammes': 'All programs',
    'operations.participants.allStages': 'All stages',
    'operations.participants.empty': 'No SMEs match the selected filters.',
    'operations.participants.loadError': 'SMEs could not be loaded.',
    'operations.participants.add': 'New SME',
    'operations.participants.create': 'Create SME',
    'operations.participants.created': 'SME account created and invitation queued.',
    'operations.participants.createError': 'SME could not be created.',
    'operations.participants.selectProgramme': 'Select a specific program before adding an SME.',
    'operations.participants.details': 'SME details',
    'operations.participants.questions': 'Onboarding questions',
    'operations.participants.documentsHint': 'Upload the program documents before reviewing the SME account.',
    'operations.participants.documentsRequired': 'Upload all required documents before continuing.',
    'operations.participants.reviewHint': 'Review the onboarding information before creating the account and sending the invitation.',
    'operations.diagnostics.subtitle': 'Create and confirm SME growth plans from their diagnostic needs.',
    'operations.diagnostics.search': 'Search SME name',
    'operations.diagnostics.allStatuses': 'All statuses',
    'operations.diagnostics.draft': 'Draft',
    'operations.diagnostics.confirmed': 'Confirmed',
    'operations.diagnostics.confirmedPlans': 'Confirmed plans',
    'operations.diagnostics.draftPlans': 'Draft plans',
    'operations.diagnostics.interventions': 'Interventions',
    'operations.diagnostics.requiredInterventions': 'Required interventions',
    'operations.diagnostics.interventionsHint': 'Add one intervention per line. Duplicate entries are removed automatically.',
    'operations.diagnostics.confirmPlan': 'Confirm plan',
    'operations.diagnostics.empty': 'No diagnostic plans match the selected filters.',
    'operations.diagnostics.loadError': 'Diagnostic plans could not be loaded.',
    'operations.diagnostics.saved': 'Diagnostic plan saved.',
    'operations.diagnostics.confirmedMessage': 'Diagnostic plan confirmed.',
    'operations.diagnostics.saveError': 'Diagnostic plan could not be saved.',
    'operations.diagnostics.strengths': 'Strengths',
    'operations.diagnostics.weaknesses': 'Weaknesses',
    'operations.diagnostics.opportunities': 'Opportunities',
    'operations.diagnostics.threats': 'Threats',
    'operations.diagnostics.noSwot': 'No SWOT items captured.',
    'operations.diagnostics.searchInterventions': 'Search interventions',
    'operations.diagnostics.allAreas': 'All support areas',
    'operations.diagnostics.noInterventions': 'No interventions match the selected filters.',
    'operations.diagnostics.reviewHint': 'Review the required interventions before confirming the growth plan.',
    'operations.diagnostics.noSelectedInterventions': 'No interventions selected yet.',
    'applicant.application.title': 'Program application',
    'applicant.application.loading': 'Loading application',
    'applicant.application.loadError': 'The application could not be prepared.',
    'applicant.application.notFound': 'This program is not available.',
    'applicant.application.details': 'Your details',
    'applicant.application.profile': 'Program profile',
    'applicant.application.noQuestions': 'This program has no additional questions.',
    'applicant.application.ready': 'Ready to submit',
    'applicant.application.reviewHint': 'Review your details, then submit your application for assessment.',
    'applicant.application.submit': 'Submit application',
    'applicant.application.submitted': 'Your application has been submitted.',
    'applicant.application.error': 'Your application could not be submitted.',
    'applicant.application.motivation': 'Motivation',
    'applicant.application.completeProfile': 'Complete profile',
    'applicant.application.profileRequired': 'Complete your applicant profile before applying to a program.',
    'applicant.application.profileReused': 'Your saved profile details will be included automatically.',
    'operations.compliance.documents': 'Documents',
    'operations.compliance.missing': 'Missing',
    'operations.compliance.participantCompliance': 'SME compliance',
    'operations.compliance.search': 'Search SME name',
    'operations.compliance.allParticipants': 'All SMEs',
    'operations.compliance.onlyActionNeeded': 'Only action needed',
    'operations.compliance.onlyCompliant': 'Only compliant',
    'operations.compliance.addDocument': 'Add document',
    'operations.compliance.scan': 'Scan',
    'operations.compliance.scanAll': 'Scan all SMEs',
    'operations.compliance.scanOneComplete': 'Compliance scan completed.',
    'operations.compliance.scanAllComplete': 'Compliance scan completed for {{count}} SMEs.',
    'operations.compliance.scanError': 'Compliance scan could not be completed.',
    'operations.compliance.scanNotConfigured': 'Compliance scan endpoint is not configured.',
    'operations.compliance.editDocument': 'Edit compliance document',
    'operations.compliance.loadError': 'Compliance records could not be loaded.',
    'operations.compliance.selectParticipant': 'Select an SME.',
    'operations.compliance.updated': 'Document updated.',
    'operations.compliance.added': 'Document added.',
    'operations.compliance.duplicate': 'This SME already has that document type. Edit the existing record instead.',
    'operations.compliance.saveError': 'Document could not be saved.',
    'operations.compliance.queryReasonRequired': 'Add a reason before querying a document.',
    'operations.compliance.verified': 'Document verified.',
    'operations.compliance.queried': 'Document queried.',
    'operations.compliance.participant': 'SME Name',
    'operations.compliance.score': 'Compliance score',
    'operations.compliance.empty': 'No compliance records match the selected filters.',
    'operations.compliance.noDocuments': 'No compliance documents uploaded.',
    'operations.compliance.documentType': 'Document type',
    'operations.compliance.documentName': 'Document name',
    'operations.compliance.issueDate': 'Issue date',
    'operations.compliance.expiryDate': 'Expiry date',
    'operations.compliance.chooseFile': 'Choose file',
    'operations.compliance.saveDocument': 'Save document',
    'operations.compliance.verifyDocument': 'Verify document',
    'operations.compliance.query': 'Query',
    'operations.compliance.verify': 'Verify',
    'operations.compliance.queryReason': 'Query reason',
    'operations.compliance.queryReasonPlaceholder': 'Required when querying a document',
    'operations.applications.review': 'Application review',
    'operations.applications.search': 'Search applications',
    'operations.applications.all': 'All',
    'operations.applications.pending': 'Pending',
    'operations.applications.accepted': 'Accepted',
    'operations.applications.rejected': 'Rejected',
    'operations.applications.allProvinces': 'All provinces',
    'operations.applications.allBeeLevels': 'All B-BBEE levels',
    'operations.applications.allGenders': 'All genders',
    'operations.applications.details': 'Application details',
    'operations.applications.confirmDecision': 'Confirm application decision',
    'operations.applications.updateStatus': 'Update status',
    'operations.applications.change': 'Change',
    'operations.applications.to': 'to',
    'operations.applications.loadError': 'Applications could not be loaded.',
    'operations.applications.updated': 'Application status updated.',
    'operations.applications.updateError': 'Application status could not be updated.',
    'operations.applications.applied': 'Applied',
    'operations.applications.aiScore': 'AI score',
    'operations.applications.aiReview': 'AI review',
    'operations.applications.program': 'Program',
    'operations.applications.motivation': 'Motivation',
    'operations.applications.challenges': 'Challenges',
    'operations.applications.decision': 'Decision',
    'operations.applications.aiRecommendation': 'AI recommendation',
    'operations.applications.justification': 'Justification',
    'operations.applications.noJustification': 'No AI justification is available yet.',
    'operations.applications.empty': 'No applications match the selected filters.',
    'operations.applications.select': 'Select an application to view details',
    'operations.applications.growthPlan': 'Growth plan',
    'operations.applications.result': 'Result',
    'operations.applications.noAiReview': 'No AI review is available for this application.',
    'operations.applications.analytics': 'Analytics',
    'operations.applications.complianceScore': 'Compliance score',
    'operations.applications.genderBreakdown': 'Gender',
    'operations.applications.challengesWordMap': 'Common challenges',
    'operations.applications.noComplianceScore': 'No compliance score is available yet.',
    'operations.applications.noData': 'No data for the current filters.',
    'incubatee.common.loadError': 'Your program workspace could not be loaded.',
    'incubatee.common.noAcceptedProgram': 'Your accepted program workspace is not available yet.',
    'incubatee.dashboard.title': 'Incubatee dashboard',
    'incubatee.dashboard.subtitle': 'Review outstanding program actions, interventions, forms, and notifications.',
    'incubatee.dashboard.loading': 'Loading your program workspace',
    'incubatee.dashboard.pendingDocuments': 'Documents outstanding',
    'incubatee.dashboard.pendingInterventions': 'Interventions to accept',
    'incubatee.dashboard.toConfirm': 'Completions to confirm',
    'incubatee.dashboard.pendingForms': 'Forms to complete',
    'incubatee.dashboard.openTracker': 'Open tracker',
    'incubatee.dashboard.openCompliance': 'Open compliance',
    'incubatee.dashboard.decisions': 'Waiting on you',
    'incubatee.dashboard.noPendingInterventions': 'No intervention decisions need your attention.',
    'incubatee.dashboard.noToConfirm': 'No completed interventions are waiting for your confirmation.',
    'incubatee.dashboard.noOpenForms': 'No forms are waiting for you.',
    'incubatee.dashboard.noDocuments': 'Every compliance document is valid.',
    'incubatee.dashboard.notUploaded': 'Not uploaded yet',
    'incubatee.dashboard.expires': 'Expires',
    'incubatee.dashboard.actionCentre': 'Action centre',
    'incubatee.dashboard.noForms': 'No forms have been assigned yet.',
    'incubatee.forms.survey': 'Survey',
    'incubatee.forms.assessment': 'Assessment',
    'incubatee.notifications.title': 'Notifications',
    'incubatee.notifications.empty': 'No notifications yet.',
    'incubatee.notifications.markRead': 'Mark read',
    'incubatee.notifications.markUnread': 'Mark unread',
    'incubatee.notifications.markAllRead': 'Mark all as read',
    'incubatee.notifications.unreadCount': '{count} unread',
    'incubatee.notifications.allRead': 'You are all caught up',
    'incubatee.notifications.unread': 'Unread',
    'incubatee.status.awaitingAcceptance': 'Awaiting acceptance',
    'incubatee.status.awaitingConfirmation': 'Awaiting confirmation',
    'incubatee.tracker.title': 'Intervention tracker',
    'incubatee.tracker.subtitle': 'Review your growth plan, intervention assignments, delivery progress, requests, and completion decisions.',
    'incubatee.tracker.loading': 'Loading interventions',
    'incubatee.tracker.planReady': 'Your growth plan is ready for your acknowledgement.',
    'incubatee.tracker.confirmPlan': 'Acknowledge growth plan',
    'incubatee.tracker.planConfirmed': 'Growth plan acknowledged.',
    'incubatee.tracker.required': 'Required',
    'incubatee.tracker.inProgress': 'In progress',
    'incubatee.tracker.awaiting': 'Awaiting confirmation',
    'incubatee.tracker.completed': 'Completed',
    'incubatee.tracker.search': 'Search interventions',
    'incubatee.tracker.allStatuses': 'All statuses',
    'incubatee.tracker.request': 'Request intervention',
    'incubatee.tracker.requested': 'Intervention request submitted.',
    'incubatee.tracker.submitRequest': 'Submit request',
    'incubatee.tracker.intervention': 'Intervention',
    'incubatee.tracker.area': 'Area of support',
    'incubatee.tracker.facilitator': 'Facilitator',
    'incubatee.tracker.resources': 'Resources',
    'incubatee.tracker.requests': 'Intervention requests',
    'incubatee.tracker.noRequests': 'No intervention requests submitted yet.',
    'incubatee.tracker.empty': 'No interventions match the selected filters.',
    'incubatee.tracker.accept': 'Accept',
    'incubatee.tracker.decline': 'Decline',
    'incubatee.tracker.confirm': 'Confirm completion',
    'incubatee.tracker.reject': 'Reject completion',
    'incubatee.tracker.rating': 'Rating',
    'incubatee.tracker.feedback': 'Feedback',
    'incubatee.tracker.reason': 'Reason',
    'incubatee.tracker.updated': 'Intervention updated.',
    'incubatee.tracker.updateError': 'The intervention could not be updated.',
    'verification.resend': 'Resend verification email',
    'welcome.title': 'Welcome setup',
    'welcome.subtitle': 'Complete the essentials once, then move into your workspace.',
    'welcome.loading': 'Preparing your setup',
    'welcome.mobileStep': 'Step {current} of {total}',
    'welcome.step.welcome': 'Welcome',
    'welcome.step.verify': 'Verify email',
    'welcome.step.password': 'Secure account',
    'welcome.step.signature': 'Signature',
    'welcome.step.consultantSetup': 'Your operating area',
    'welcome.step.complete': 'Complete',
    'welcome.consultantSetup.title': 'Where do you operate?',
    'welcome.consultantSetup.body': 'Tell us where you are based so in-person interventions can be matched to SMEs within a practical travel distance. You can update this whenever you move.',
    'welcome.consultantSetup.location': 'Base location',
    'welcome.consultantSetup.country': 'Country',
    'welcome.consultantSetup.countryPlaceholder': 'Select a SADC country',
    'welcome.consultantSetup.province': 'Province / region',
    'welcome.consultantSetup.provincePlaceholder': 'Select a province or region',
    'welcome.consultantSetup.address': 'Physical address',
    'welcome.consultantSetup.addressPlaceholder': 'Street, suburb, town/city',
    'welcome.consultantSetup.radius': 'In-person service radius (km)',
    'welcome.consultantSetup.currency': 'Currency for your daily rate',
    'welcome.consultantSetup.continue': 'Save and continue',
    'welcome.intro.title': 'Let us get your workspace ready',
    'welcome.intro.body': 'This short setup keeps your account secure and prepares your applicant workspace.',
    'welcome.intro.verify': 'Confirm your email address',
    'welcome.intro.password': 'Review your account password',
    'welcome.intro.signature': 'Add your e-signature',
    'welcome.intro.ready': 'Continue into the correct role workspace',
    'welcome.start': 'Start setup',
    'welcome.verify.title': 'Verify your email address',
    'welcome.verify.body': 'We sent a secure verification link to {email}.',
    'welcome.verify.linkHint': 'Open the verification link in your inbox, then return here and check the status.',
    'welcome.verify.refresh': 'Check verification status',
    'welcome.verify.success': 'Your email address is verified.',
    'welcome.verify.checkInbox': 'Your email is not verified yet. Please check your inbox.',
    'welcome.verify.resent': 'A new verification email has been sent.',
    'welcome.verify.error': 'Email verification could not be checked.',
    'welcome.password.title': 'Secure your account',
    'welcome.password.body': 'Choose a strong password. The setup steps stay visible after saving so your progress remains clear.',
    'welcome.password.new': 'New password',
    'welcome.password.confirm': 'Confirm new password',
    'welcome.password.rule': 'Add an uppercase letter, a number, and a symbol.',
    'welcome.password.save': 'Save password',
    'welcome.password.saved': 'Password saved',
    'welcome.password.success': 'Your password has been updated.',
    'welcome.password.error': 'Your password could not be updated.',
    'welcome.password.relogin': 'Please sign in again, then update your password.',
    'welcome.signature.title': 'Add your signature',
    'welcome.signature.body': 'Upload a clear image of your signature. It will be used when you acknowledge plans and documents in the workspace.',
    'welcome.signature.choose': 'Choose signature image',
    'welcome.signature.required': 'Please choose a signature image.',
    'welcome.signature.save': 'Save signature',
    'welcome.signature.saved': 'Signature saved',
    'welcome.signature.success': 'Your signature has been saved.',
    'welcome.signature.error': 'Your signature could not be saved.',
    'welcome.finish.title': 'Setup complete',
    'welcome.finish.body': 'The essentials are complete. You can continue into your workspace.',
    'welcome.finish.continue': 'Continue to workspace',
    'welcome.finish.error': 'Your setup could not be completed.',
    'agent.title': 'Workspace Assistant',
    'agent.ready': 'Ready to help',
    'agent.thinking': 'Thinking...',
    'agent.open': 'Open workspace assistant',
    'agent.toggleFullscreen': 'Toggle full screen',
    'agent.typing': 'Assistant is typing',
    'agent.placeholder': 'Ask about this page...',
    'agent.send': 'Send message',
    'agent.error': 'The workspace assistant could not respond. Please try again.',
    'agent.template.explain': 'Explain what I can do on {page}.',
    'agent.template.nextSteps': 'What should I do next on {page}?',
    'agent.template.programs': 'Which available program opportunities should I review first?',
    'agent.template.tracker': 'Summarize my application progress and suggest the next step.',
    'agent.template.profile': 'What profile information should I complete before applying?',
    'agent.pageReady': 'I am ready to help with {page}. Ask me about what you can do here.',
    'agent.workspaceReady': 'I am ready to help with your workspace.',
    'applicant.profile.title': 'Applicant Profile',
    'applicant.profile.subtitle': 'Complete your personal and business details before applying to a program.',
    'applicant.profile.status': 'Profile status',
    'applicant.profile.saved': 'Saved',
    'applicant.profile.setup': 'Setup required',
    'applicant.profile.business': 'Business',
    'applicant.profile.notAdded': 'Not added',
    'applicant.profile.ownerDetails': 'Owner details',
    'applicant.profile.ownerName': 'Owner name',
    'applicant.profile.phone': 'Phone number',
    'applicant.profile.gender': 'Gender',
    'applicant.profile.businessDetails': 'Business details',
    'applicant.profile.businessName': 'SME Name',
    'applicant.profile.sector': 'Sector',
    'applicant.profile.registrationNumber': 'Registration number',
    'applicant.profile.yearsTrading': 'Years trading',
    'applicant.profile.beeLevel': 'B-BBEE level',
    'applicant.profile.operatingContext': 'Operating context',
    'applicant.profile.province': 'Province',
    'applicant.profile.city': 'City',
    'applicant.profile.address': 'Business address',
    'applicant.profile.nature': 'What does your business do?',
    'applicant.profile.eligibilityHint': 'These details will be used to assess program eligibility.',
    'applicant.profile.save': 'Save profile',
    'applicant.profile.loading': 'Loading your profile',
    'applicant.profile.loadError': 'Your profile details could not be loaded.',
    'applicant.profile.signIn': 'Please sign in before saving your profile.',
    'applicant.profile.saveSuccess': 'Your applicant profile has been saved.',
    'applicant.profile.saveError': 'Your profile could not be saved.',
    'applicant.programs.title': 'Program Discovery',
    'applicant.programs.subtitle': 'Explore opportunities and find the right incubation program for your business.',
    'applicant.programs.loading': 'Loading programs',
    'applicant.programs.error': 'Programs could not be loaded.',
    'applicant.programs.available': 'Available programs',
    'applicant.programs.open': 'Open opportunities',
    'applicant.programs.suggested': 'Suggested programs',
    'applicant.programs.matched': 'Matched opportunities',
    'applicant.programs.applications': 'Applications',
    'applicant.programs.submitted': 'Already submitted',
    'applicant.programs.all': 'All programs',
    'applicant.programs.search': 'Search programs',
    'applicant.programs.allTypes': 'All types',
    'applicant.programs.general': 'General',
    'applicant.programs.untitled': 'Untitled program',
    'applicant.programs.noDetails': 'No program description provided.',
    'applicant.programs.applied': 'Already applied',
    'applicant.programs.view': 'View program',
    'applicant.programs.empty': 'No programs match the selected filters.',
    'applicant.programs.details': 'Program details',
    'applicant.programs.start': 'Start application',
    'applicant.tracker.title': 'Application Tracker',
    'applicant.tracker.subtitle': 'Follow the progress of applications submitted for your business.',
    'applicant.tracker.error': 'Your applications could not be loaded.',
    'applicant.tracker.total': 'Total applications',
    'applicant.tracker.pending': 'Pending',
    'applicant.tracker.accepted': 'Accepted',
    'applicant.tracker.rejected': 'Rejected',
    'applicant.tracker.all': 'All statuses',
    'applicant.tracker.search': 'Search by program',
    'applicant.tracker.program': 'Program',
    'applicant.tracker.status': 'Status',
    'applicant.tracker.compliance': 'Compliance',
    'applicant.tracker.fallbackProgram': 'Program application',
    'applicant.tracker.empty': 'You have not submitted any applications yet.',
    'shell.workspace': 'Workspace',
    'shell.allProjects': 'All Projects',
    'shell.allPrograms': 'All Programs',
    'shell.searchWorkspace': 'Search workspace',
    'shell.searchPlaceholder': 'Search SMEs, documents, tasks and reports...',
    'shell.searchHint': 'Workspace search will surface useful records across the platform as each module is restored.',
    'shell.searchAreas': 'Search across your workspace',
    'shell.searchParticipants': 'SMEs',
    'shell.searchDocuments': 'Documents and evidence',
    'shell.searchTasks': 'Tasks and appointments',
    'shell.searchReports': 'Reports and analytics',
    'shell.searchNoResults': 'Record search is ready for its data indexes. No matching workspace records are available yet.',
    'placeholder.title': 'Page coming soon',
    'placeholder.subtitle': 'This destination is registered and ready for its module to be restored.',
    'notFound.subtitle': 'Sorry, the page you visited does not exist.',
    'auth.loginTitle': 'Welcome back',
    'auth.loginSubtitle': 'Sign in to continue managing your incubation workspace.',
    'auth.loginButton': 'Log in',
    'auth.loginTab': 'Login',
    'auth.signupTab': 'Sign up',
    'auth.signupTitle': 'Create your account',
    'auth.signupSubtitle': 'Create your login details. Thuso will guide your account setup next.',
    'auth.signupButton': 'Create account',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.fullName': 'Full name',
    'auth.confirmPassword': 'Confirm password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.continueWith': 'Or sign in with',
    'auth.google': 'Continue with Google',
    'auth.facebook': 'Continue with Facebook',
    'auth.resetTitle': 'Reset password',
    'auth.sendResetLink': 'Send reset link',
    'auth.resetBody': 'Enter your email address and we will send you a password reset link.',
    'usage.title': 'Usage Analytics',
    'usage.subtitle': 'See how long people stay logged in and which pages they use most.',
    'usage.loading': 'Loading usage analytics',
    'usage.loadError': 'Usage analytics could not be loaded. Check the Firestore access rules for admin accounts.',
    'usage.forbidden': 'Only administrators can view usage analytics.',
    'usage.totalTime': 'Total logged-in time',
    'usage.sessions': 'Sessions',
    'usage.activeNow': 'Active now',
    'usage.mostUsed': 'Most-used page',
    'usage.pagesChart': 'Most-used pages',
    'usage.usersChart': 'Logged-in time by user',
    'usage.usersTable': 'User activity',
    'usage.pagesTable': 'Page activity',
    'usage.user': 'User',
    'usage.role': 'Role',
    'usage.loggedInTime': 'Logged-in time',
    'usage.lastSeen': 'Last seen',
    'usage.page': 'Page',
    'usage.visits': 'Visits',
    'usage.uniqueUsers': 'Unique users',
    'usage.timeUsed': 'Time used',
    'usage.minutes': 'Minutes',
    'usage.unknownUser': 'Unknown user',
    'usage.noData': 'No data yet',
    'usage.filters': 'Usage filters',
    'usage.allRoles': 'All roles',
    'usage.allUsers': 'All users',
    'usage.allRoutes': 'All pages',
    'usage.activityTrend': 'Activity trend',
    'usage.overview': 'Overview',
    'usage.users': 'Users',
    'usage.pages': 'Pages',
  },
  zu: {
    'nav.landing': 'Ikhaya',
    'nav.auth': 'Ngena',
    'nav.welcome': 'Siyakwamukela',
    'nav.dashboard': 'Ideshibhodi',
    'nav.profile': 'Iphrofayela',
    'nav.onboarding': 'Qala',
    'nav.marketplace': 'Thola Umeluleki',
    'nav.connectionRequests': 'Izicelo Zoxhumano',
    'nav.consultantServices': 'Amasevisi Nezindleko Zami',
    'nav.consultantProfile': 'Iphrofayela Yomeluleki',
    'nav.consultantVerification': 'Ukuqinisekiswa Kwabeluleki',
    'nav.availability': 'Ukutholakala',
    'nav.mySmes': 'Ama-SME Ami',
    'nav.programs': 'Izinhlelo',
    'nav.inquiries': 'Imibuzo',
    'nav.applicationTracker': 'Ukulandela Isicelo',
    'nav.metrics': 'Izilinganiso',
    'nav.tracker': 'Ukulandelela',
    'nav.staff': 'Abasebenzi',
    'nav.viewAll': 'Buka Konke',
    'nav.operations': 'Imisebenzi',
    'nav.timesheet': 'Ithebula lesikhathi',
    'nav.manageTeam': 'Phatha Iqembu',
    'nav.activity': 'Umsebenzi',
    'nav.tasks': 'Imisebenzi',
    'nav.participants': 'Ababambiqhaza',
    'nav.applications': 'Izicelo',
    'nav.incubatees': 'Abasafufusa',
    'nav.compliance': 'Ukuhambisana',
    'nav.riskRegister': 'Irejista Yobungozi',
    'nav.impactAnalysis': 'Ukuhlaziywa Komthelela',
    'nav.diagnosticPlans': 'Izinhlelo Zokuhlola',
    'nav.myDiagnosticPlan': 'Uhlelo Lwami Lokuhlola',
    'nav.interventions': 'Ukungenelela',
    'nav.documentLibrary': 'Umtapo Wamadokhumenti',
    'nav.monitoring': 'Ukuqapha',
    'nav.assignInterventions': 'Yabela ukungenelela',
    'nav.assignedInterventions': 'Engabelwe kona',
    'nav.feedback': 'Impendulo',
    'nav.assignments': 'Izabelo',
    'nav.appointments': 'Izikhathi',
    'nav.movs': 'Ama-MOV',
    'nav.surveys': 'Izinhlolovo',
    'nav.surveyBuilder': 'Umakhi wenhlolovo',
    'nav.courses': 'Izifundo',
    'nav.courseBuilder': 'Umakhi wesifundo',
    'nav.reports': 'Imibiko',
    'nav.esgScorecard': 'Ikhadi Le-ESG',
    'nav.esgPerformance': 'Ukusebenza Kwe-ESG Ngamunye',
    'nav.portfolio': 'Iphothifoliyo',
    'nav.sectors': 'Imikhakha',
    'nav.programPerformance': 'Ukusebenza Kwezinhlelo',
    'nav.structure': 'Iminyango Namahhovisi',
    'nav.changeRequests': 'Izicelo Zoshintsho',
    'nav.assistant': 'Umsizi',
    'nav.setup': 'Ukusetha',
    'nav.incubateeWorkspace': 'Indawo Yomfukameli',
    'nav.roadmap': 'Uhlelo Lwendlela',
    'nav.businessPlan': 'Uhlelo Lwebhizinisi',
    'nav.strategicPlan': 'Uhlelo Lwesu',
    'nav.pitchCoach': 'Umqeqeshi Wokwethula',
    'nav.agentRegistry': 'Irejista Yama-Agent',
    'nav.agentAvailability': 'Ukutholakala Kwama-Agent',
    'nav.agentRatings': 'Izilinganiso Zama-Agent',
    'nav.users': 'Abasebenzisi',
    'nav.usageAnalytics': 'Ukuhlaziywa Kokusetshenziswa',
    'nav.emailOperations': 'Ukuphathwa Kwama-imeyili',
    'nav.settings': 'Izilungiselelo',
    'nav.companySettings': 'Izilungiselelo Zenkampani',
    'consultant.common.assignments': 'Izabelo',
    'consultant.common.intervention': 'Ukungenelela',
    'consultant.common.sme': 'I-SME',
    'consultant.common.program': 'Uhlelo',
    'consultant.common.progress': 'Inqubekelaphambili',
    'consultant.common.due': 'Umnqamulajuqu',
    'consultant.common.noDueDate': 'Awukho umnqamulajuqu',
    'consultant.status.pending': 'Kulindile',
    'consultant.status.inprogress': 'Kuyaqhubeka',
    'consultant.status.completed': 'Kuqediwe',
    'consultant.status.rejected': 'Kwaliwe',
    'consultant.status.overdue': 'Sekwedlule isikhathi',
    'consultant.metrics.assigned': 'Kwabiwe',
    'consultant.metrics.inProgress': 'Kuyaqhubeka',
    'consultant.metrics.completed': 'Kuqediwe',
    'consultant.metrics.attention': 'Okudinga ukunakwa',
    'consultant.dashboard.title': 'Indawo Yomeluleki',
    'consultant.dashboard.subtitle': 'Umugqa wakho womsebenzi, impendulo, nemibiko endaweni eyodwa.',
    'consultant.dashboard.loading': 'Kulayishwa indawo yomeluleki',
    'consultant.dashboard.openInterventions': 'Vula ukungenelela',
    'consultant.dashboard.assignedHint': 'Konke ukungenelela okwabelwe wena',
    'consultant.dashboard.pendingHint': '{count} kulindele ukwamukelwa',
    'consultant.dashboard.completionHint': '{rate}% isilinganiso sokuqeda',
    'consultant.dashboard.overdueHint': 'Imisebenzi esedlule isikhathi',
    'consultant.dashboard.deliveryQueue': 'Umugqa Wokulethwa',
    'consultant.dashboard.noActive': 'Akukho ukungenelela okusebenzayo okwabelwe wena.',
    'consultant.dashboard.deliveryHealth': 'Isimo Sokulethwa',
    'consultant.dashboard.noAssignments': 'Ayikho idatha yezabelo okwamanje',
    'consultant.dashboard.recentFeedback': 'Impendulo Yakamuva',
    'consultant.dashboard.noFeedback': 'Impendulo izovela ngemva kokuthi ama-SME eqede ukubuyekeza.',
    'consultant.dashboard.averageFeedback': 'Isilinganiso sempendulo',
    'consultant.dashboard.reviewFeedback': 'Buyekeza impendulo',
    'consultant.dashboard.buildReport': 'Yakha umbiko',
    'consultant.feedback.title': 'Impendulo',
    'consultant.feedback.loading': 'Kulayishwa impendulo',
    'consultant.feedback.filters': 'Izihlungi zempendulo',
    'consultant.feedback.search': 'Sesha i-SME, ukungenelela, noma ukuphawula',
    'consultant.feedback.exportCsv': 'Thumela i-CSV',
    'consultant.feedback.average': 'Isilinganiso',
    'consultant.feedback.lowRatings': 'Izilinganiso eziphansi',
    'consultant.feedback.lowRatingsHint': 'Izinkanyezi ezi-2 noma ngaphansi',
    'consultant.feedback.newest': 'Okusha kuqala',
    'consultant.feedback.oldest': 'Okudala kuqala',
    'consultant.feedback.highest': 'Isilinganiso esiphezulu',
    'consultant.feedback.lowest': 'Isilinganiso esiphansi',
    'consultant.feedback.ratingDistribution': 'Ukusabalala Kwezilinganiso',
    'consultant.feedback.noRated': 'Akukho mpendulo elinganisiwe okwamanje',
    'consultant.feedback.comments': 'Amazwana',
    'consultant.feedback.empty': 'Ayikho impendulo ehambisana nezihlungi zamanje.',
    'consultant.feedback.noComment': 'Akukho mazwana abhaliwe aqoshiwe.',
    'consultant.feedback.noDate': 'Usuku aluqoshiwe',
    'consultant.feedback.unrated': 'Akukalinganiswa',
    'consultant.feedback.starLabel': 'inkanyezi {count}',
    'consultant.feedback.feedbackCount': 'Inani lempendulo',
    'consultant.feedback.ratings': 'Izilinganiso',
    'consultant.feedback.rating': 'Isilinganiso',
    'consultant.feedback.comment': 'Amazwana',
    'consultant.reports.loading': 'Kulayishwa idatha yombiko',
    'consultant.reports.scope': 'Ububanzi bombiko',
    'consultant.reports.thisMonth': 'Le nyanga',
    'consultant.reports.thisQuarter': 'Le kota',
    'consultant.reports.thisYear': 'Lo nyaka',
    'consultant.reports.custom': 'Okwenziwe ngokwezifiso',
    'consultant.reports.template': 'Isifanekiso',
    'consultant.reports.downloadCsv': 'Landa i-CSV',
    'consultant.reports.activeHint': '{count} kuyaqhubeka',
    'consultant.reports.avgRating': 'Isilinganiso esimaphakathi',
    'consultant.reports.ratedHint': '{count} kulinganisiwe',
    'consultant.reports.statusMix': 'Ukuhlanganiswa Kwezimo',
    'consultant.reports.programmeWorkload': 'Umthwalo Wohlelo',
    'consultant.reports.empty': 'Ayikho idatha yombiko kulesi sikhathi',
    'consultant.reports.noProgrammeData': 'Ayikho idatha yohlelo kulesi sikhathi',
    'consultant.reports.detail': 'Imininingwane Yombiko',
    'consultant.reports.narrative': 'Isifinyezo',
    'consultant.reports.summary': 'Kuqediwe {completed} kwezingu-{total} ezabelwe, futhi {overdue} kudinga ukunakwa.',
    'consultant.reports.templateNote': 'Le datha isebenzisa isixhumanisi sesifanekiso sombiko esifanayo ukuze imisebenzi ilande i-CSV yomeluleki.',
    'common.loading': 'Kuyalayishwa...',
    'common.save': 'Londoloza',
    'common.cancel': 'Khansela',
    'common.create': 'Dala',
    'common.edit': 'Hlela',
    'common.delete': 'Susa',
    'common.back': 'Emuva',
    'common.backHome': 'Buyela ekhaya',
    'common.dashboard': 'Iya kudeshibhodi',
    'common.lightMode': 'Khanya',
    'common.darkMode': 'Mnyama',
    'common.search': 'Sesha',
    'common.logout': 'Phuma',
    'common.close': 'Vala',
    'common.name': 'Igama',
    'common.email': 'I-imeyili',
    'common.role': 'Indima',
    'common.status': 'Isimo',
    'common.actions': 'Izenzo',
    'common.active': 'Kuyasebenza',
    'common.inactive': 'Akusebenzi',
    'common.all': 'Konke',
    'common.progress': 'Inqubekelaphambili',
    'common.noDate': 'Alukho usuku',
    'common.noCode': 'Ayikho ikhodi',
    'common.refresh': 'Vuselela',
    'common.overview': 'Uhlolojikelele',
    'common.business': 'Ibhizinisi',
    'common.noEmail': 'Ayikho i-imeyili',
    'common.unassigned': 'Akukabiwa',
    'common.type': 'Uhlobo',
    'common.document': 'Idokhumenti',
    'common.verification': 'Ukuqinisekisa',
    'common.owner': 'Umnikazi',
    'common.phone': 'Ucingo',
    'common.completed': 'okuqediwe',
    'common.sector': 'Umkhakha',
    'common.province': 'Isifundazwe',
    'common.beeLevel': 'Izinga le-B-BBEE',
    'common.gender': 'Ubulili',
    'common.score': 'Amaphuzu',
    'common.review': 'Buyekeza',
    'common.view': 'Buka',
    'common.expiry': 'Ukuphelelwa yisikhathi',
    'common.notes': 'Amanothi',
    'common.file': 'Ifayela',
    'common.saving': 'Kuyalondolozwa...',
    'common.download': 'Landa',
    'permissions.featureAccess': 'Ukufinyelela ezicini',
    'permissions.fullAccess': 'Ukufinyelela okuphelele ezicini',
    'permissions.assignInterventions': 'Yabela ukungenelela',
    'permissions.trackInterventions': 'Landela intuthuko yokungenelela',
    'permissions.viewDiagnosticPlans': 'Buka izinhlelo zokuhlola',
    'permissions.manageDiagnosticPlans': 'Dala futhi uhlele izinhlelo zokuhlola',
    'permissions.viewApplications': 'Buka izicelo',
    'permissions.manageApplications': 'Buyekeza futhi unqume izicelo',
    'permissions.viewParticipants': 'Buka ababambiqhaza',
    'permissions.viewCompliance': 'Buka amarekhodi okuhambisana',
    'permissions.manageCompliance': 'Phatha amarekhodi okuhambisana',
    'permissions.viewReports': 'Buka imibiko',
    'director.programs.title': 'Ukusebenza Kwezinhlelo',
    'director.programs.loading': 'Kulayishwa ukusebenza kwezinhlelo',
    'director.programs.loadError': 'Ukusebenza kwezinhlelo akukwazanga ukulayishwa.',
    'director.programs.programs': 'Izinhlelo',
    'director.programs.smes': 'Ama-SME',
    'director.programs.overdue': 'Sekwedlule isikhathi',
    'director.programs.filters': 'Izihlungi zezinhlelo',
    'director.programs.search': 'Sesha izinhlelo',
    'director.programs.progressChart': 'Inqubekelaphambili Yezinhlelo',
    'director.programs.riskChart': 'Ukuhlukaniswa Kobungozi Ngohlelo',
    'director.programs.avgProgress': 'Inqubekelaphambili emaphakathi',
    'director.programs.completion': 'Ukuqedwa',
    'director.programs.highRisk': 'Ubungozi obuphezulu',
    'director.programs.program': 'Uhlelo',
    'director.programs.revenue': 'Imali engenayo',
    'director.programs.empty': 'Azikho izinhlelo ezifana nezihlungi zamanje.',
    'director.risk.low': 'Phansi',
    'director.risk.medium': 'Maphakathi',
    'director.risk.high': 'Phezulu',
    'director.structure.title': 'Iminyango Namahhovisi',
    'director.structure.loading': 'Kulayishwa ukusetha kwesakhiwo',
    'director.structure.loadError': 'Ukusetha kwesakhiwo akukwazanga ukulayishwa.',
    'director.structure.saveError': 'Ukusetha kwesakhiwo akukwazanga ukulondolozwa.',
    'director.structure.saved': 'Ukusetha kwesakhiwo kulondoloziwe.',
    'director.structure.departments': 'Iminyango',
    'director.structure.department': 'Umnyango',
    'director.structure.offices': 'Amahhovisi',
    'director.structure.office': 'Ihhovisi',
    'director.structure.activeDepartments': 'Iminyango esebenzayo',
    'director.structure.activeOffices': 'Amahhovisi asebenzayo',
    'director.structure.notEnabled': 'Iminyango namahhovisi akukanikwa amandla kule nkampani.',
    'director.structure.enableHint': 'Vula iminyango noma amagatsha/amahhovisi kuzilungiselelo zenkampani kuqala, noma uthumele isicelo sokwengeza ukusetha.',
    'director.structure.filters': 'Izihlungi zesakhiwo',
    'director.structure.search': 'Sesha igama, ikhodi, noma umphathi',
    'director.structure.add': 'Engeza',
    'director.structure.empty': 'Awekho amarekhodi esakhiwo afana nezihlungi zamanje.',
    'director.structure.manager': 'Umphathi',
    'director.structure.code': 'Ikhodi',
    'director.structure.managerName': 'Igama lomphathi',
    'director.structure.managerEmail': 'I-imeyili yomphathi',
    'director.structure.notes': 'Amanothi',
    'director.structure.nameRequired': 'Igama liyadingeka.',
    'director.reports.title': 'Imibiko Yomqondisi',
    'director.reports.loading': 'Kulayishwa imibiko yomqondisi',
    'director.reports.loadError': 'Idatha yombiko womqondisi ayikwazanga ukulayishwa.',
    'director.reports.scope': 'Ububanzi bombiko womqondisi',
    'director.reports.programHealth': 'Impilo Yezinhlelo',
    'director.reports.sectorExposure': 'Ukubonakala Kwemikhakha',
    'director.reports.riskDistribution': 'Ukuhlukaniswa Kobungozi Bephothifoliyo',
    'director.reports.smes': 'Ama-SME',
    'director.reports.sme': 'I-SME',
    'director.reports.growth': 'Ukukhula',
    'director.reports.risk': 'Ubungozi',
    'director.reports.noPortfolio': 'Awekho amarekhodi ephothifoliyo atholakele.',
    'director.reports.noSectors': 'Akukho ukubonakala kwemikhakha okutholakele.',
    'admin.dashboard.title': 'Uhlolojikelele Lwesistimu',
    'admin.dashboard.subtitle': 'Qapha ama-akhawunti, amaphrojekthi asebenzayo, izicelo namaphutha akamuva okuthumela.',
    'admin.dashboard.users': 'Abasebenzisi',
    'admin.dashboard.activeUsers': 'Abasebenzisi abasebenzayo',
    'admin.dashboard.companies': 'Izinkampani',
    'admin.dashboard.recentErrors': 'Amaphutha akamuva',
    'admin.dashboard.source': 'Umthombo',
    'admin.dashboard.error': 'Iphutha',
    'admin.dashboard.recorded': 'Kuqoshiwe',
    'admin.dashboard.noErrors': 'Awekho amaphutha akamuva okuthumela.',
    'admin.dashboard.loadError': 'Uhlolojikelele lwesistimu alukwazanga ukulayishwa.',
    'emailOps.title': 'Ukuphathwa kwama-imeyili',
    'emailOps.sent': 'Okuthunyelwe',
    'emailOps.failed': 'Okuhlulekile',
    'emailOps.rejected': 'Okwenqatshiwe',
    'emailOps.bounced': 'Okubuyile',
    'emailOps.suppressed': 'Okuvinjiwe',
    'emailOps.invalid': 'Ama-imeyili angalungile',
    'emailOps.delivery': 'Umsebenzi wokuthumela',
    'emailOps.send': 'Thumela i-imeyili',
    'emailOps.queue': 'Faka i-imeyili kulayini',
    'emailOps.queued': 'I-imeyili ifakwe kulayini wokuthunyelwa.',
    'emailOps.loadError': 'Umsebenzi wokuthumela ama-imeyili awukwazanga ukulayishwa.',
    'emailOps.sendError': 'I-imeyili ayikwazanga ukufakwa kulayini.',
    'emailOps.recipient': 'Umamukeli',
    'emailOps.source': 'Umthombo',
    'emailOps.detail': 'Imininingwane',
    'emailOps.reason': 'Isizathu',
    'emailOps.failures': 'Ukuhluleka',
    'emailOps.recorded': 'Kuqoshiwe',
    'emailOps.subject': 'Isihloko',
    'emailOps.message': 'Umlayezo',
    'emailOps.bounceHint': 'Izibalo zama-imeyili abuyile zidinga impendulo evela kumhlinzeki wakho we-SMTP. Ukwenqatshwa okusheshayo namakheli avinjiwe kuyalandelelwa lapha.',
    'common.moreFilters': 'Ezinye izihlungi',
    'common.filters': 'Izihlungi',
    'common.applyFilters': 'Sebenzisa izihlungi',
    'common.continue': 'Qhubeka',
    'operations.common.needsAction': 'Kudingeka isenzo',
    'operations.staff.members': 'Abasebenzi',
    'operations.staff.consultants': 'Abeluleki',
    'operations.staff.consultant': 'Umeluleki',
    'operations.staff.projectAdmins': 'Abaphathi bephrojekthi',
    'operations.staff.projectAdmin': 'Umphathi wephrojekthi',
    'operations.staff.directory': 'Uhlu lwabasebenzi',
    'operations.staff.search': 'Sesha abasebenzi',
    'operations.staff.add': 'Engeza umsebenzi',
    'operations.staff.edit': 'Hlela umsebenzi',
    'operations.staff.save': 'Londoloza umsebenzi',
    'operations.staff.empty': 'Abekho abasebenzi abafana nosesho lwakho.',
    'operations.staff.removeConfirm': 'Susa leli rekhodi lomsebenzi?',
    'operations.staff.loadError': 'Abasebenzi abakwazanga ukulayishwa.',
    'operations.staff.updated': 'Umsebenzi ubuyekeziwe.',
    'operations.staff.added': 'Umsebenzi wengeziwe.',
    'operations.staff.saveError': 'Umsebenzi akakwazanga ukulondolozwa.',
    'operations.staff.removed': 'Umsebenzi ususiwe.',
    'operations.staff.removeError': 'Umsebenzi akakwazanga ukususwa.',
    'operations.participants.enterprise': 'Ibhizinisi',
    'operations.participants.programme': 'Uhlelo',
    'operations.participants.stage': 'Isigaba',
    'operations.participants.compliant': 'Kuyahambisana',
    'operations.participants.completedInterventions': 'Ukungenelela okuqediwe',
    'operations.participants.search': 'Sesha ababambiqhaza',
    'operations.participants.allProgrammes': 'Zonke izinhlelo',
    'operations.participants.allStages': 'Zonke izigaba',
    'operations.participants.empty': 'Abekho ababambiqhaza abafana nezihlungi ezikhethiwe.',
    'operations.participants.loadError': 'Ababambiqhaza abakwazanga ukulayishwa.',
    'operations.participants.add': 'Umbambiqhaza omusha',
    'operations.participants.create': 'Dala umbambiqhaza',
    'operations.participants.created': 'I-akhawunti yombambiqhaza idaliwe futhi isimemo sifakwe kulayini.',
    'operations.participants.createError': 'Umbambiqhaza akakwazanga ukudalwa.',
    'operations.participants.selectProgramme': 'Khetha uhlelo oluthile ngaphambi kokungeza umbambiqhaza.',
    'operations.participants.details': 'Imininingwane yombambiqhaza',
    'operations.participants.questions': 'Imibuzo yokwamukela',
    'operations.participants.documentsHint': 'Layisha amadokhumenti ohlelo ngaphambi kokubuyekeza i-akhawunti yombambiqhaza.',
    'operations.participants.documentsRequired': 'Layisha wonke amadokhumenti adingekayo ngaphambi kokuqhubeka.',
    'operations.participants.reviewHint': 'Buyekeza imininingwane yokwamukela ngaphambi kokudala i-akhawunti nokuthumela isimemo.',
    'operations.diagnostics.subtitle': 'Dala futhi uqinisekise izinhlelo zokukhula zababambiqhaza ngezidingo zabo zokuhlolwa.',
    'operations.diagnostics.search': 'Sesha umbambiqhaza noma ibhizinisi',
    'operations.diagnostics.allStatuses': 'Zonke izimo',
    'operations.diagnostics.draft': 'Okusalungiswa',
    'operations.diagnostics.confirmed': 'Kuqinisekisiwe',
    'operations.diagnostics.confirmedPlans': 'Izinhlelo eziqinisekisiwe',
    'operations.diagnostics.draftPlans': 'Izinhlelo ezisalungiswa',
    'operations.diagnostics.interventions': 'Ukungenelela',
    'operations.diagnostics.requiredInterventions': 'Ukungenelela okudingekayo',
    'operations.diagnostics.interventionsHint': 'Faka ukungenelela okukodwa emugqeni ngamunye. Okuphindaphindiwe kuyasuswa ngokuzenzakalelayo.',
    'operations.diagnostics.confirmPlan': 'Qinisekisa uhlelo',
    'operations.diagnostics.empty': 'Azikho izinhlelo zokuhlola ezihambisana nezihlungi.',
    'operations.diagnostics.loadError': 'Izinhlelo zokuhlola azikwazanga ukulayishwa.',
    'operations.diagnostics.saved': 'Uhlelo lokuhlola lulondoloziwe.',
    'operations.diagnostics.confirmedMessage': 'Uhlelo lokuhlola luqinisekisiwe.',
    'operations.diagnostics.saveError': 'Uhlelo lokuhlola alukwazanga ukulondolozwa.',
    'operations.diagnostics.strengths': 'Amandla',
    'operations.diagnostics.weaknesses': 'Ubuthakathaka',
    'operations.diagnostics.opportunities': 'Amathuba',
    'operations.diagnostics.threats': 'Izinsongo',
    'operations.diagnostics.noSwot': 'Azikho izinto ze-SWOT ezifakiwe.',
    'operations.diagnostics.searchInterventions': 'Sesha ukungenelela',
    'operations.diagnostics.allAreas': 'Zonke izindawo zosizo',
    'operations.diagnostics.noInterventions': 'Akukho ukungenelela okuhambisana nezihlungi.',
    'operations.diagnostics.reviewHint': 'Buyekeza ukungenelela okudingekayo ngaphambi kokuqinisekisa uhlelo lokukhula.',
    'operations.diagnostics.noSelectedInterventions': 'Akukho ukungenelela okukhethiwe okwamanje.',
    'applicant.application.title': 'Isicelo sohlelo',
    'applicant.application.loading': 'Kulayishwa isicelo',
    'applicant.application.loadError': 'Isicelo asikwazanga ukulungiswa.',
    'applicant.application.notFound': 'Lolu hlelo alutholakali.',
    'applicant.application.details': 'Imininingwane yakho',
    'applicant.application.profile': 'Iphrofayela yohlelo',
    'applicant.application.noQuestions': 'Lolu hlelo alunayo imibuzo eyengeziwe.',
    'applicant.application.ready': 'Sekulungele ukuthunyelwa',
    'applicant.application.reviewHint': 'Buyekeza imininingwane yakho bese uthumela isicelo sakho ukuze sihlolwe.',
    'applicant.application.submit': 'Thumela isicelo',
    'applicant.application.submitted': 'Isicelo sakho sithunyelwe.',
    'applicant.application.error': 'Isicelo sakho asikwazanga ukuthunyelwa.',
    'applicant.application.motivation': 'Isizathu',
    'applicant.application.completeProfile': 'Qedela iphrofayela',
    'applicant.application.profileRequired': 'Qedela iphrofayela yakho yombambiqhaza ngaphambi kokufaka isicelo sohlelo.',
    'applicant.application.profileReused': 'Imininingwane yephrofayela yakho egciniwe izofakwa ngokuzenzakalelayo.',
    'operations.compliance.documents': 'Amadokhumenti',
    'operations.compliance.missing': 'Okungekho',
    'operations.compliance.participantCompliance': 'Ukuhambisana kwababambiqhaza',
    'operations.compliance.search': 'Sesha umbambiqhaza',
    'operations.compliance.allParticipants': 'Bonke ababambiqhaza',
    'operations.compliance.onlyActionNeeded': 'Okudinga isenzo kuphela',
    'operations.compliance.onlyCompliant': 'Okuhambisanayo kuphela',
    'operations.compliance.addDocument': 'Engeza idokhumenti',
    'operations.compliance.scan': 'Skena',
    'operations.compliance.scanAll': 'Skena wonke ama-SME',
    'operations.compliance.scanOneComplete': 'Ukuskena ukuhambisana kuqediwe.',
    'operations.compliance.scanAllComplete': 'Ukuskena ukuhambisana kuqediwe kuma-SME angu-{{count}}.',
    'operations.compliance.scanError': 'Ukuskena ukuhambisana akukwazanga ukuqedwa.',
    'operations.compliance.scanNotConfigured': 'Indawo yokuskena ukuhambisana ayilungiselelwanga.',
    'operations.compliance.editDocument': 'Hlela idokhumenti yokuhambisana',
    'operations.compliance.loadError': 'Amarekhodi okuhambisana awakwazanga ukulayishwa.',
    'operations.compliance.selectParticipant': 'Khetha umbambiqhaza.',
    'operations.compliance.updated': 'Idokhumenti ibuyekeziwe.',
    'operations.compliance.added': 'Idokhumenti yengeziwe.',
    'operations.compliance.duplicate': 'Lo mbambiqhaza usenalo lolo hlobo lwedokhumenti. Hlela irekhodi elikhona.',
    'operations.compliance.saveError': 'Idokhumenti ayikwazanga ukulondolozwa.',
    'operations.compliance.queryReasonRequired': 'Engeza isizathu ngaphambi kokubuza ngedokhumenti.',
    'operations.compliance.verified': 'Idokhumenti iqinisekisiwe.',
    'operations.compliance.queried': 'Idokhumenti ibuziwe.',
    'operations.compliance.participant': 'Umbambiqhaza',
    'operations.compliance.score': 'Amaphuzu okuhambisana',
    'operations.compliance.empty': 'Awekho amarekhodi okuhambisana afana nezihlungi ezikhethiwe.',
    'operations.compliance.noDocuments': 'Awekho amadokhumenti okuhambisana alayishiwe.',
    'operations.compliance.documentType': 'Uhlobo lwedokhumenti',
    'operations.compliance.documentName': 'Igama ledokhumenti',
    'operations.compliance.issueDate': 'Usuku lokukhishwa',
    'operations.compliance.expiryDate': 'Usuku lokuphelelwa',
    'operations.compliance.chooseFile': 'Khetha ifayela',
    'operations.compliance.saveDocument': 'Londoloza idokhumenti',
    'operations.compliance.verifyDocument': 'Qinisekisa idokhumenti',
    'operations.compliance.query': 'Buza',
    'operations.compliance.verify': 'Qinisekisa',
    'operations.compliance.queryReason': 'Isizathu sombuzo',
    'operations.compliance.queryReasonPlaceholder': 'Kuyadingeka lapho kubuzwa ngedokhumenti',
    'operations.applications.review': 'Ukubuyekezwa kwezicelo',
    'operations.applications.search': 'Sesha izicelo',
    'operations.applications.all': 'Konke',
    'operations.applications.pending': 'Kusalindiwe',
    'operations.applications.accepted': 'Kwamukelwe',
    'operations.applications.rejected': 'Kunqatshiwe',
    'operations.applications.allProvinces': 'Zonke izifundazwe',
    'operations.applications.allBeeLevels': 'Wonke amazinga e-B-BBEE',
    'operations.applications.allGenders': 'Bonke ubulili',
    'operations.applications.details': 'Imininingwane yesicelo',
    'operations.applications.confirmDecision': 'Qinisekisa isinqumo sesicelo',
    'operations.applications.updateStatus': 'Buyekeza isimo',
    'operations.applications.change': 'Shintsha',
    'operations.applications.to': 'kube',
    'operations.applications.loadError': 'Izicelo azikwazanga ukulayishwa.',
    'operations.applications.updated': 'Isimo sesicelo sibuyekeziwe.',
    'operations.applications.updateError': 'Isimo sesicelo asikwazanga ukubuyekezwa.',
    'operations.applications.applied': 'Kufakwe',
    'operations.applications.aiScore': 'Amaphuzu e-AI',
    'operations.applications.aiReview': 'Ukubuyekezwa kwe-AI',
    'operations.applications.program': 'Uhlelo',
    'operations.applications.motivation': 'Ugqozi',
    'operations.applications.challenges': 'Izinselelo',
    'operations.applications.decision': 'Isinqumo',
    'operations.applications.aiRecommendation': 'Isincomo se-AI',
    'operations.applications.justification': 'Incazelo',
    'operations.applications.noJustification': 'Ayikho incazelo ye-AI okwamanje.',
    'operations.applications.empty': 'Azikho izicelo ezifana nezihlungi ezikhethiwe.',
    'operations.applications.select': 'Khetha isicelo ukuze ubone imininingwane',
    'operations.applications.growthPlan': 'Uhlelo lokukhula',
    'operations.applications.result': 'Umphumela',
    'operations.applications.noAiReview': 'Ayikho ukubuyekezwa kwe-AI okutholakalayo kulesi sicelo.',
    'operations.applications.analytics': 'Ukuhlaziywa kwedatha',
    'operations.applications.complianceScore': 'Amaphuzu okuhambisana',
    'operations.applications.genderBreakdown': 'Ubulili',
    'operations.applications.challengesWordMap': 'Izinselelo ezivamile',
    'operations.applications.noComplianceScore': 'Awekho amaphuzu okuhambisana okutholakalayo okwamanje.',
    'operations.applications.noData': 'Ayikho idatha yezihlungi ezikhethiwe.',
    'incubatee.common.loadError': 'Indawo yakho yohlelo ayikwazanga ukulayishwa.',
    'incubatee.common.noAcceptedProgram': 'Indawo yakho yohlelo olwamukelwe ayikatholakali.',
    'incubatee.dashboard.title': 'Ideshibhodi yomfukameli',
    'incubatee.dashboard.subtitle': 'Buyekeza izenzo zohlelo, ukungenelela, amafomu nezaziso.',
    'incubatee.dashboard.loading': 'Kulayishwa indawo yakho yohlelo',
    'incubatee.dashboard.pendingDocuments': 'Amadokhumenti asele',
    'incubatee.dashboard.pendingInterventions': 'Ukungenelela okumele kwamukelwe',
    'incubatee.dashboard.toConfirm': 'Ukuqedwa okumele kuqinisekiswe',
    'incubatee.dashboard.pendingForms': 'Amafomu okumele agcwaliswe',
    'incubatee.dashboard.openTracker': 'Vula ukulandelela',
    'incubatee.dashboard.openCompliance': 'Vula ukuthobela',
    'incubatee.dashboard.decisions': 'Kulindwe wena',
    'incubatee.dashboard.noPendingInterventions': 'Azikho izinqumo zokungenelela ezidinga isenzo sakho.',
    'incubatee.dashboard.noToConfirm': 'Akukho ukungenelela okuqediwe okulinde ukuqinisekiswa nguwe.',
    'incubatee.dashboard.noOpenForms': 'Awekho amafomu akulindile.',
    'incubatee.dashboard.noDocuments': 'Wonke amadokhumenti okuthobela asemthethweni.',
    'incubatee.dashboard.notUploaded': 'Alikalayishwa',
    'incubatee.dashboard.expires': 'Liphelelwa yisikhathi',
    'incubatee.dashboard.actionCentre': 'Isikhungo sezenzo',
    'incubatee.dashboard.noForms': 'Awekho amafomu owabelwe wona okwamanje.',
    'incubatee.forms.survey': 'Inhlolovo',
    'incubatee.forms.assessment': 'Ukuhlola',
    'incubatee.notifications.title': 'Izaziso',
    'incubatee.notifications.empty': 'Azikho izaziso okwamanje.',
    'incubatee.notifications.markRead': 'Maka njengokufundiwe',
    'incubatee.notifications.markUnread': 'Maka njengokungafundiwe',
    'incubatee.notifications.markAllRead': 'Maka konke njengokufundiwe',
    'incubatee.notifications.unreadCount': 'Okungu-{count} okungafundiwe',
    'incubatee.notifications.allRead': 'Usufunde konke',
    'incubatee.notifications.unread': 'Okungafundiwe',
    'incubatee.status.awaitingAcceptance': 'Kulindelwe ukwamukela',
    'incubatee.status.awaitingConfirmation': 'Kulindelwe ukuqinisekisa',
    'incubatee.tracker.title': 'Ukulandelela ukungenelela',
    'incubatee.tracker.subtitle': 'Buyekeza uhlelo lwakho lokukhula, ukungenelela, intuthuko, izicelo nezinqumo zokuqeda.',
    'incubatee.tracker.loading': 'Kulayishwa ukungenelela',
    'incubatee.tracker.planReady': 'Uhlelo lwakho lokukhula lulungele ukwamukelwa.',
    'incubatee.tracker.confirmPlan': 'Yamukela uhlelo lokukhula',
    'incubatee.tracker.planConfirmed': 'Uhlelo lokukhula lwamukelwe.',
    'incubatee.tracker.required': 'Okudingekayo',
    'incubatee.tracker.inProgress': 'Kuyaqhubeka',
    'incubatee.tracker.awaiting': 'Kulindelwe ukuqinisekisa',
    'incubatee.tracker.completed': 'Kuqediwe',
    'incubatee.tracker.search': 'Sesha ukungenelela',
    'incubatee.tracker.allStatuses': 'Zonke izimo',
    'incubatee.tracker.request': 'Cela ukungenelela',
    'incubatee.tracker.requested': 'Isicelo sokungenelela sithunyelwe.',
    'incubatee.tracker.submitRequest': 'Thumela isicelo',
    'incubatee.tracker.intervention': 'Ukungenelela',
    'incubatee.tracker.area': 'Indawo yosizo',
    'incubatee.tracker.facilitator': 'Umsizi',
    'incubatee.tracker.resources': 'Izinsiza',
    'incubatee.tracker.requests': 'Izicelo zokungenelela',
    'incubatee.tracker.noRequests': 'Azikho izicelo zokungenelela ezithunyelwe okwamanje.',
    'incubatee.tracker.empty': 'Akukho ukungenelela okuhambisana nezihlungi.',
    'incubatee.tracker.accept': 'Yamukela',
    'incubatee.tracker.decline': 'Nqaba',
    'incubatee.tracker.confirm': 'Qinisekisa ukuqedwa',
    'incubatee.tracker.reject': 'Nqaba ukuqedwa',
    'incubatee.tracker.rating': 'Isilinganiso',
    'incubatee.tracker.feedback': 'Impendulo',
    'incubatee.tracker.reason': 'Isizathu',
    'incubatee.tracker.updated': 'Ukungenelela kubuyekeziwe.',
    'incubatee.tracker.updateError': 'Ukungenelela akukwazanga ukubuyekezwa.',
    'verification.resend': 'Thumela kabusha i-imeyili yokuqinisekisa',
    'welcome.title': 'Ukusetha ukwamukela',
    'welcome.subtitle': 'Qedela okubalulekile kanye bese ungena endaweni yakho yokusebenza.',
    'welcome.loading': 'Kulungiswa ukusetha kwakho',
    'welcome.mobileStep': 'Isinyathelo {current} kwezi-{total}',
    'welcome.step.welcome': 'Siyakwamukela',
    'welcome.step.verify': 'Qinisekisa i-imeyili',
    'welcome.step.password': 'Vikela i-akhawunti',
    'welcome.step.signature': 'Isiginesha',
    'welcome.step.consultantSetup': 'Indawo osebenza kuyo',
    'welcome.step.complete': 'Kuqediwe',
    'welcome.intro.title': 'Masilungise indawo yakho yokusebenza',
    'welcome.intro.body': 'Lokhu kusetha okufushane kuvikela i-akhawunti yakho futhi kulungise indawo yakho yomfakisicelo.',
    'welcome.intro.verify': 'Qinisekisa ikheli lakho le-imeyili',
    'welcome.intro.password': 'Buyekeza iphasiwedi ye-akhawunti',
    'welcome.intro.signature': 'Faka isiginesha yakho',
    'welcome.intro.ready': 'Qhubeka uye endaweni efanele',
    'welcome.start': 'Qala ukusetha',
    'welcome.verify.title': 'Qinisekisa ikheli lakho le-imeyili',
    'welcome.verify.body': 'Sithumele isixhumanisi esivikelekile sokuqinisekisa ku-{email}.',
    'welcome.verify.linkHint': 'Vula isixhumanisi sokuqinisekisa ebhokisini lemilayezo, bese ubuyela lapha uhlole isimo.',
    'welcome.verify.refresh': 'Hlola isimo sokuqinisekisa',
    'welcome.verify.success': 'Ikheli lakho le-imeyili liqinisekisiwe.',
    'welcome.verify.checkInbox': 'I-imeyili ayikaqinisekiswa. Sicela uhlole ibhokisi lakho lemilayezo.',
    'welcome.verify.resent': 'Kuthunyelwe i-imeyili entsha yokuqinisekisa.',
    'welcome.verify.error': 'Ukuqinisekiswa kwe-imeyili akukwazanga ukuhlolwa.',
    'welcome.password.title': 'Vikela i-akhawunti yakho',
    'welcome.password.body': 'Khetha iphasiwedi eqinile. Izinyathelo zihlala zibonakala ngemva kokulondoloza.',
    'welcome.password.new': 'Iphasiwedi entsha',
    'welcome.password.confirm': 'Qinisekisa iphasiwedi entsha',
    'welcome.password.rule': 'Faka uhlamvu olukhulu, inombolo nophawu.',
    'welcome.password.save': 'Londoloza iphasiwedi',
    'welcome.password.saved': 'Iphasiwedi ilondoloziwe',
    'welcome.password.success': 'Iphasiwedi yakho ibuyekeziwe.',
    'welcome.password.error': 'Iphasiwedi ayikwazanga ukubuyekezwa.',
    'welcome.password.relogin': 'Sicela ungene futhi, bese ubuyekeza iphasiwedi yakho.',
    'welcome.signature.title': 'Faka isiginesha yakho',
    'welcome.signature.body': 'Layisha isithombe esicacile sesiginesha yakho. Sizosetshenziswa lapho uqinisekisa amapulani namadokhumenti.',
    'welcome.signature.choose': 'Khetha isithombe sesiginesha',
    'welcome.signature.required': 'Sicela ukhethe isithombe sesiginesha.',
    'welcome.signature.save': 'Londoloza isiginesha',
    'welcome.signature.saved': 'Isiginesha ilondoloziwe',
    'welcome.signature.success': 'Isiginesha yakho ilondoloziwe.',
    'welcome.signature.error': 'Isiginesha ayikwazanga ukulondolozwa.',
    'welcome.finish.title': 'Ukusetha kuqediwe',
    'welcome.finish.body': 'Okubalulekile kuqediwe. Ungaqhubeka uye endaweni yakho yokusebenza.',
    'welcome.finish.continue': 'Qhubeka uye endaweni yokusebenza',
    'welcome.finish.error': 'Ukusetha kwakho akukwazanga ukuqedwa.',
    'agent.title': 'Umsizi Wendawo Yokusebenza',
    'agent.ready': 'Ulungele ukusiza',
    'agent.thinking': 'Uyacabanga...',
    'agent.open': 'Vula umsizi wendawo yokusebenza',
    'agent.toggleFullscreen': 'Shintsha isikrini esigcwele',
    'agent.typing': 'Umsizi uyabhala',
    'agent.placeholder': 'Buza ngaleli khasi...',
    'agent.send': 'Thumela umlayezo',
    'agent.error': 'Umsizi akakwazanga ukuphendula. Sicela uzame futhi.',
    'agent.template.explain': 'Chaza engingakwenza ku-{page}.',
    'agent.template.nextSteps': 'Yini okufanele ngiyenze ngokulandelayo ku-{page}?',
    'agent.template.programs': 'Yiziphi izinhlelo ezitholakalayo okufanele ngizibuke kuqala?',
    'agent.template.tracker': 'Fingqa intuthuko yezicelo zami bese uphakamisa okulandelayo.',
    'agent.template.profile': 'Yimiphi imininingwane yephrofayela okufanele ngiyiqedele ngaphambi kokufaka isicelo?',
    'agent.pageReady': 'Ngikulungele ukusiza nge-{page}. Buza ngalokho ongakwenza lapha.',
    'agent.workspaceReady': 'Ngikulungele ukusiza ngendawo yakho yokusebenza.',
    'applicant.profile.title': 'Iphrofayela Yomfakisicelo',
    'applicant.profile.subtitle': 'Qedela imininingwane yakho neyebhizinisi ngaphambi kokufaka isicelo.',
    'applicant.profile.status': 'Isimo sephrofayela',
    'applicant.profile.saved': 'Kulondoloziwe',
    'applicant.profile.setup': 'Kudingeka ukusethwa',
    'applicant.profile.business': 'Ibhizinisi',
    'applicant.profile.notAdded': 'Akukafakwa',
    'applicant.profile.ownerDetails': 'Imininingwane yomnikazi',
    'applicant.profile.ownerName': 'Igama lomnikazi',
    'applicant.profile.phone': 'Inombolo yocingo',
    'applicant.profile.gender': 'Ubulili',
    'applicant.profile.businessDetails': 'Imininingwane yebhizinisi',
    'applicant.profile.businessName': 'Igama lebhizinisi',
    'applicant.profile.sector': 'Umkhakha',
    'applicant.profile.registrationNumber': 'Inombolo yokubhalisa',
    'applicant.profile.yearsTrading': 'Iminyaka yokusebenza',
    'applicant.profile.beeLevel': 'Izinga le-B-BBEE',
    'applicant.profile.operatingContext': 'Indawo yokusebenza',
    'applicant.profile.province': 'Isifundazwe',
    'applicant.profile.city': 'Idolobha',
    'applicant.profile.address': 'Ikheli lebhizinisi',
    'applicant.profile.nature': 'Ibhizinisi lakho lenzani?',
    'applicant.profile.eligibilityHint': 'Le mininingwane izosetshenziswa ukuhlola ukufaneleka kohlelo.',
    'applicant.profile.save': 'Londoloza iphrofayela',
    'applicant.profile.loading': 'Kulayishwa iphrofayela yakho',
    'applicant.profile.loadError': 'Imininingwane yephrofayela ayikwazanga ukulayishwa.',
    'applicant.profile.signIn': 'Sicela ungene ngaphambi kokulondoloza iphrofayela.',
    'applicant.profile.saveSuccess': 'Iphrofayela yakho ilondoloziwe.',
    'applicant.profile.saveError': 'Iphrofayela ayikwazanga ukulondolozwa.',
    'applicant.programs.title': 'Ukuthola Izinhlelo',
    'applicant.programs.subtitle': 'Hlola amathuba uthole uhlelo olufanele ibhizinisi lakho.',
    'applicant.programs.loading': 'Kulayishwa izinhlelo',
    'applicant.programs.error': 'Izinhlelo azikwazanga ukulayishwa.',
    'applicant.programs.available': 'Izinhlelo ezitholakalayo',
    'applicant.programs.open': 'Amathuba avulekile',
    'applicant.programs.suggested': 'Izinhlelo eziphakanyisiwe',
    'applicant.programs.matched': 'Amathuba afanayo',
    'applicant.programs.applications': 'Izicelo',
    'applicant.programs.submitted': 'Ezifakiwe',
    'applicant.programs.all': 'Zonke izinhlelo',
    'applicant.programs.search': 'Sesha izinhlelo',
    'applicant.programs.allTypes': 'Zonke izinhlobo',
    'applicant.programs.general': 'Okuvamile',
    'applicant.programs.untitled': 'Uhlelo olungenagama',
    'applicant.programs.noDetails': 'Ayikho incazelo yohlelo enikeziwe.',
    'applicant.programs.applied': 'Isicelo sesifakiwe',
    'applicant.programs.view': 'Buka uhlelo',
    'applicant.programs.empty': 'Azikho izinhlelo ezihambisana nezihlungi.',
    'applicant.programs.details': 'Imininingwane yohlelo',
    'applicant.programs.start': 'Qala isicelo',
    'applicant.tracker.title': 'Ukulandela Isicelo',
    'applicant.tracker.subtitle': 'Landela intuthuko yezicelo ezifakwe ibhizinisi lakho.',
    'applicant.tracker.error': 'Izicelo zakho azikwazanga ukulayishwa.',
    'applicant.tracker.total': 'Zonke izicelo',
    'applicant.tracker.pending': 'Kusalindiwe',
    'applicant.tracker.accepted': 'Kwamukelwe',
    'applicant.tracker.rejected': 'Kunqatshiwe',
    'applicant.tracker.all': 'Zonke izimo',
    'applicant.tracker.search': 'Sesha ngohlelo',
    'applicant.tracker.program': 'Uhlelo',
    'applicant.tracker.status': 'Isimo',
    'applicant.tracker.compliance': 'Ukuhambisana',
    'applicant.tracker.fallbackProgram': 'Isicelo sohlelo',
    'applicant.tracker.empty': 'Awukafaki izicelo okwamanje.',
    'shell.workspace': 'Indawo yokusebenza',
    'shell.allProjects': 'Wonke Amaphrojekthi',
    'shell.allPrograms': 'Zonke izinhlelo',
    'shell.searchWorkspace': 'Sesha endaweni yokusebenza',
    'shell.searchPlaceholder': 'Sesha ababambiqhaza, amadokhumenti, imisebenzi nemibiko...',
    'shell.searchHint': 'Ukusesha kuzoveza amarekhodi awusizo njengoba amamodyuli ebuyiselwa.',
    'shell.searchAreas': 'Sesha kuyo yonke indawo yokusebenza',
    'shell.searchParticipants': 'Ababambiqhaza nama-SME',
    'shell.searchDocuments': 'Amadokhumenti nobufakazi',
    'shell.searchTasks': 'Imisebenzi nezikhathi',
    'shell.searchReports': 'Imibiko nokuhlaziya',
    'shell.searchNoResults': 'Ukusesha amarekhodi sekulungile ukuze kuxhunywe idatha. Awekho amarekhodi afanayo okwamanje.',
    'placeholder.title': 'Ikhasi liyeza',
    'placeholder.subtitle': 'Le ndawo isibhalisiwe futhi isilungele ukubuyiselwa kwemodyuli yayo.',
    'notFound.subtitle': 'Uxolo, ikhasi olivakashele alikho.',
    'auth.loginTitle': 'Siyakwamukela futhi',
    'auth.loginSubtitle': 'Ngena ukuze uqhubeke nokuphatha indawo yakho yokufukamela.',
    'auth.loginButton': 'Ngena',
    'auth.loginTab': 'Ngena',
    'auth.signupTab': 'Bhalisa',
    'auth.signupTitle': 'Dala i-akhawunti yakho',
    'auth.signupSubtitle': 'Dala imininingwane yakho yokungena. UThuso uzokuqondisa ekusetheni i-akhawunti yakho ngokulandelayo.',
    'auth.signupButton': 'Dala i-akhawunti',
    'auth.email': 'Ikheli le-imeyili',
    'auth.password': 'Iphasiwedi',
    'auth.fullName': 'Igama eligcwele',
    'auth.confirmPassword': 'Qinisekisa iphasiwedi',
    'auth.forgotPassword': 'Ukhohlwe iphasiwedi?',
    'auth.continueWith': 'Noma ngena nge',
    'auth.google': 'Qhubeka nge-Google',
    'auth.facebook': 'Qhubeka nge-Facebook',
    'auth.resetTitle': 'Setha kabusha iphasiwedi',
    'auth.sendResetLink': 'Thumela isixhumanisi',
    'auth.resetBody': 'Faka ikheli lakho le-imeyili sizokuthumelela isixhumanisi sokusetha kabusha iphasiwedi.',
    'usage.title': 'Ukuhlaziywa Kokusetshenziswa',
    'usage.subtitle': 'Bona ukuthi abantu bangena isikhathi esingakanani nokuthi yimaphi amakhasi asetshenziswa kakhulu.',
    'usage.loading': 'Kulayishwa ukuhlaziywa kokusetshenziswa',
    'usage.loadError': 'Ukuhlaziywa kokusetshenziswa akukwazanga ukulayishwa. Hlola imithetho ye-Firestore yama-akhawunti omlawuli.',
    'usage.forbidden': 'Abaphathi kuphela abangabuka ukuhlaziywa kokusetshenziswa.',
    'usage.totalTime': 'Isikhathi sonke sokungena',
    'usage.sessions': 'Izikhathi zokungena',
    'usage.activeNow': 'Abasebenzayo manje',
    'usage.mostUsed': 'Ikhasi elisetshenziswa kakhulu',
    'usage.pagesChart': 'Amakhasi asetshenziswa kakhulu',
    'usage.usersChart': 'Isikhathi sokungena ngomsebenzisi',
    'usage.usersTable': 'Umsebenzi womsebenzisi',
    'usage.pagesTable': 'Umsebenzi wekhasi',
    'usage.user': 'Umsebenzisi',
    'usage.role': 'Indima',
    'usage.loggedInTime': 'Isikhathi sokungena',
    'usage.lastSeen': 'Ugcine ukubonakala',
    'usage.page': 'Ikhasi',
    'usage.visits': 'Ukuvakasha',
    'usage.uniqueUsers': 'Abasebenzisi abahlukene',
    'usage.timeUsed': 'Isikhathi esisetshenzisiwe',
    'usage.minutes': 'Amaminithi',
    'usage.unknownUser': 'Umsebenzisi ongaziwa',
    'usage.noData': 'Ayikho idatha okwamanje',
    'usage.filters': 'Izihlungi zokusetshenziswa',
    'usage.allRoles': 'Zonke izindima',
    'usage.allUsers': 'Bonke abasebenzisi',
    'usage.allRoutes': 'Wonke amakhasi',
    'usage.activityTrend': 'Umkhondo womsebenzi',
    'usage.overview': 'Ukubuka konke',
    'usage.users': 'Abasebenzisi',
    'usage.pages': 'Amakhasi',
  },
}
